version: 0.0

os: linux

files:
  - source: /
    destination: /opt/my-app

hooks:
  BeforeInstall:
    - location: install_dependencies
      timeout: 300
      runas: root

  ApplicationStart:
    - location: star_server
      timeout: 300
      runas: root

  ApplicationStop:
    - location: stop_server
      timeout: 300
      runas: root
