#!/bin/bash
docker login -u $(dockernusers)  -p $(dockerpassword)

# Pull the Docker image from the registry
docker pull smritiorganization/ubuntu/apache2:latest

# Run the Docker container
docker run -d -p 8080:8080 smritiorganization/ubuntu/apache2:latest
